### ISSUE TITLE
[FEATURE] Design `UpdateGroupFragment`

### ISSUE THREAD

**Issue by Mohd-Sherif** [mohamed-sallam/awb-android#23]
## Description
Add basic UI of `UpdateGroupFragment`

## Tasks
- [ ] Create vertical `RecyclerView` of Apps.
- [ ] Create **cancel** button.
- [ ] Create **save** button.
- [ ] Create **search** icon.
- [ ] Create `CheckBox` for SelectAll.

## Basic Design
![image](https://user-images.githubusercontent.com/111144120/204395782-a5cd0c48-7faa-403c-9f59-9e8608128a86.png)
