### ISSUE TITLE
[FEATURE] Design `HomeFragment`

### ISSUE THREAD

**Issue by yousef-genedy** [mohamed-sallam/awb-android#25]
## Description
Add basic UI of home fragment.

## Tasks
- [x] Add a spinner `TimePicker`.
- [x] Create add button.
- [x] Add a lock button.
- [x] Add icons in action bar.
- [x] Add horizontal `RecyclerView` of groups.

## Basic Design
![image](https://user-images.githubusercontent.com/115221628/204400348-20168814-bc81-4773-a77e-7c151e6316cc.png)
