### ISSUE TITLE
[FEATURE] Create Data Entities for Room Database (1/2)

### ISSUE THREAD

**Issue by mohamed-sallam** [mohamed-sallam/awb-android#30]
This is the first part of implementing our entities. Future part(s) will cover the remaining entities.
## Tasks
- [x] Init `Device` as entity.
- [x] Init `Group` as entity.
- [x] Init `DetoxPeriod` as entity.
- [x] Create `BlockedApp` entity.

## ERD
![image](https://user-images.githubusercontent.com/59128458/205203000-781081db-124c-45a9-b40d-26743ea98ba7.png)
