### ISSUE TITLE
[FEATURE] Create `DeviceWithGroups` adapter

### ISSUE THREAD

**Issue by Abdurrahman-Salah-ad-Din** [mohamed-sallam/awb-android#47]
## Tasks
- [x] Create device with groups Item XML file
- [x] Add Data Binding to device_with _groups_Item.xml
- [x] Create Adapter 
- [x] Implement Diff callBack
    - [x] override the `equals()` for both `Group` and `DeviceWithGroup`
- [ ] Implement onClick listener
