### ISSUE TITLE
[REFACTOR] Edit `GroupsAdapter`

### ISSUE THREAD

**Issue by Abdurrahman-Salah-ad-Din** [mohamed-sallam/awb-android#52]
## Tasks
- [x] Edit `Group` class.
    - [x] Add constructor pass name.
    - [x] Add a getter for the name.
    - [x] Override equal method.
- [x] Create Differ class that inherits from `DiffUtil.ItemCallback<Group>`
- [x] Bind the group with the group in the data binding
- [x] Add `parent` to `rootView` argument and `false` to `attachToRoot` argument
- [ ] Create long press listener
