### ISSUE TITLE
[DOCUMENTATION] Add GitHub Conventions Document

### ISSUE THREAD

**Issue by standard-librarian** [mohamed-sallam/awb-android#63]
Add GitHub conventions document for documenting existing conventions and add new conventions for issues and PRs.
# Tasks
- [ ] Document the existing convention for:
    - [ ] Branches
    - [ ] Commit title
    - [ ] Merge commit message
    - [ ] PR title
    - [ ] Issue title
- [ ] Add issue templates
- [ ] Add PR templates
- [ ] Add atomic commit rules and body
# References 
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
